// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xftbjlybxiuqttskkzmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmdGJqbHlieGl1cXR0c2trem1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NTEwNjYsImV4cCI6MjA3MzEyNzA2Nn0.3vAn7K_4NyNoMEimS3Bg05oLLIkwT1XjD8Tnb6pM688";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});